### PR TITLE
Add gh pages and move cap-website as main eclipse-cap website for the project

### PR DESCRIPTION
**Pull request by ticapix**
As we don't have other sub website, moving the current one as the main one for the project.

move cap-website as main eclipse-cap website for the project

### CODE REVIEW

**Comment by netomi** [comment]
I fixed the conflicts, I set the gh pages method to workflow as this the existing method unless you wanna switch to legacy which I strongly advise not to do.

**Comment by ticapix** [comment]
@netomi thank you,

I'm used to build all my docs with mkdocs-material and I would be happy to replicate the docs generation from the .eclipsefdn repo [itself](https://github.com/eclipse-dataspace-cap/.eclipsefdn/blob/main/.github/workflows/build-page.yml)

**Comment by netomi** [comment]
you could also set the homepage property to https://eclipse-dataspace-cap.github.io to easily navigate to the GH Pages site.

**Pull request merged**
